spring.application.name=proyecto
server.port=8081
spring.datasource.url=jdbc:mysql://tokaido.proxy.rlwy.net:40899/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=JHIpeUOmljsRJidQucjqJNWmCrPAkcEd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Configuración de Correo (API Resend)
resend.api.key=${RESEND_API_KEY}

# Actuator / Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=gymlabs-backend
